export default {
  namespaced: true,
  state: {
    items: [
      '裝潢用材料',
      '模板用材料',
      '代加工備料',
      '傢俱用材料',
      '包裝用材料',
      '特殊訂製品',
    ],
    itemsEng: [
      'Decoration Materials',
      'Template Materials',
      'Customized Preparation Materials',
      'Furnishing Materials',
      'Packaging Materials',
      'Special Order Products',
    ],
    products: [
      {
        name: '夾板',
        nameEng: 'Plywood',
        open: false,
        height: 0,
        items: [
          '俄羅斯夾板',
          '印尼夾板',
          '馬來西亞夾板',
          '大陸夾板',
          '波麗夾板',
          '防火夾板',
          '地板',
          '雷射板',
          '彎曲板',
          '模板',
          '補模用夾板',
          '機械模夾板',
          '抽牆板',
          '環保膠夾板',
          '酚醛膠防水模板',
        ],
        itemsEng: [
          'Russia Plywood',
          'Indonesian Plywood',
          'Malaysian Plywood',
          'China Plywood',
          'Polyester Plywood',
          'Fire-proof Plywood',
          'Flooring',
          'Laser Panel',
          'Bending Plywood',
          'Concrete Plywood',
          'Make Up Concrete Plywood',
          'Mechanical Model Plywood',
          'Drawer Panel',
          'F1 Plywood',
          'WBP (F1) Concrete Plywood',
        ],
      },
      {
        name: '木心板',
        nameEng: 'Blockboard',
        open: false,
        height: 0,
        items: [
          '麻六甲木心板',
          '柳安木心板',
          '波麗木心板',
          '防火木心板',
        ],
        itemsEng: [
          'Falcata Blockboard',
          'Meranti Blockboard',
          'Polyester Blockboard',
          'Fire-proof Blockboard',
        ],
      },
      {
        name: '角材',
        nameEng: 'Timber',
        open: false,
        height: 0,
        items: [
          '層積角材',
          '防火角材',
          '防腐角材',
          '酚醛膠環保角材',
        ],
        itemsEng: [
          'LVL',
          'Fire-proof SAWN Timber',
          'Preservation SAWN Timber',
          'WBP(F1) SAWN Timber',
        ],
      },
      {
        name: '木製品',
        nameEng: 'Wooden Product',
        open: false,
        height: 0,
        items: [
          '俄羅斯各類木材',
          '紐西蘭松木',
          '南方松防腐材',
          '門斗',
          '門片',
        ],
        itemsEng: [
          'RussiaAll Kinds Of Wood Products',
          'New Zealand Radiata Pine Timber',
          'Southern Pine Preservation Timber',
          'Door Frame',
          'Door Panel',
        ],
      },
      {
        name: '人造板',
        nameEng: 'Wood-based Panel',
        open: false,
        height: 0,
        items: [
          '角柱',
          '密迪板',
          '塑合板',
        ],
        itemsEng: [
          'Particle Prism',
          'MDF',
          'Particle Board',
        ],
      },
      {
        name: '防火板',
        nameEng: 'Fire-proof Board',
        open: false,
        height: 0,
        items: [
          '矽酸鈣板',
          '石膏板',
          '水泥板',
        ],
        itemsEng: [
          'Calcium Silicate Board',
          'Gypsum Board',
          'Cement Board',
        ],
      },
      {
        name: '其他材料',
        nameEng: 'Others',
        open: false,
        height: 0,
        items: [
          'PVC發泡板',
          '美耐板',
          '防潮布',
          '鋁箔隔熱棉捲',
          '隔音棉捲',
          'PP瓦楞板',
        ],
        itemsEng: [
          'PVC Foam Sheet',
          'High Pressure Laminate',
          'Water-proof Cloth',
          'Aluminium-foil Heat Insulating Cotton Roll',
          'Sound-Proof Cotton Roll',
          'PP Corrugated Board',
        ],
      },
    ],
  },
  mutations: {
    changeProductsValue(state, { idx, key, value }) {
      state.products[idx][key] = value;
    },
  },
  getters: {

  },

  actions: {

  },
};
